name: deploy_website

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ brianp/new-website-2022 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy_website"
  deploy_website:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          # s3_website ruby/java uploader does not support 11. :-(
          java-version: '8'
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          ruby-version: '2.7.5'
      # Runs a set of commands using the runners shell
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          JEKYLL_ENV: production
        name: Deploy website
        run: |
          bundle exec jekyll build --trace
          # bundle exec jekyll algolia
          bundle exec s3_website push
          aws cloudfront update-function --name fusionauth-website-request-handler --function-code src/cloudfront/request-handler.js
          # aws cloudfront publish-function --name fusionauth-website-request-handler
        shell: bash
