name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Find PR
    - uses: actions/github-script@0.6.0
      id: pr
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        result-encoding: string
        script: |
          const result = await github.repos.listPullRequestsAssociatedWithCommit({
            owner: context.payload.repository.owner.name,
            repo: context.payload.repository.name,
            commit_sha: context.payload.head_commit.id
          })
          return result.data[0].number;
    - name: File Changes
      id: file_changes
      uses: trilom/file-changes-action@v1.2.4
      with: 
        prNumber: ${{ steps.pr.outputs.results }}
    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      with:
        styles: |
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        files: '${{ steps.file_changes.outputs.files_modified }}'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
